# Generated by Django 2.2.6 on 2020-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='主机ip')),
                ('file', models.CharField(max_length=256, verbose_name='文件列表')),
                ('count', models.IntegerField(default=0, verbose_name='文件数量')),
                ('size', models.CharField(max_length=32, verbose_name='文件大小')),
                ('back_time', models.DateTimeField(auto_now_add=True, verbose_name='备份时间')),
                ('user_name', models.CharField(max_length=16, verbose_name='备份人')),
            ],
            options={
                'db_table': 'back_up_detail',
            },
        ),
    ]
