# Generated by Django 2.2.6 on 2020-05-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BackModel',
            new_name='BackUp',
        ),
    ]

